### ISSUE TITLE
Doctrine ORM YAML definitions

### ISSUE THREAD

**Issue by kappaj** [Prometee/SyliusVIESClientPlugin#6]
Docs:
I think it would be good for users with YAML orm definitions to know, that they have to create yml files. This worked for me:

config/doctrine/Address.orm.yml:

```
App\Entity\Address :
    type: entity
    table: sylius_address

    fields:
        vatNumber:
            name: vat_number
            type: string
            nullable: true
```

config/doctrine/Channel.orm.yml:

```
App\Entity\Channel:
    type: entity
    table: sylius_channel

    manyToOne:
        baseCountry:
            targetEntity: Sylius\Component\Addressing\Model\CountryInterface
            fetch: EAGER
            joinColumn:
                name: base_country_id
                onDelete: "SET NULL"
        europeanZone:
            targetEntity: Sylius\Component\Addressing\Model\ZoneInterface
            fetch: EAGER
            joinColumn:
                name: european_zone_id
                onDelete: "SET NULL"
```
